services:
  - type: web
    name: bfhl-api
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: BFHL_USER_ID
        value: shreeya_02082005
      - key: BFHL_EMAIL
        value: shreeya1132.be23@chitkara.edu.in
      - key: BFHL_ROLL_NUMBER
        value: "2310991132"
