spring.application.name=bfhl-api
server.port=${PORT:8080}

# Update these with your details before submitting (or set env vars on host)
bfhl.user-id=${BFHL_USER_ID:shreeya_02082005}
bfhl.email=${BFHL_EMAIL:shreeya1132.be23@chitkara.edu.in}
bfhl.roll-number=${BFHL_ROLL_NUMBER:2310991132}
